baseURL = "/"
languageCode = "en-us"
title = "iPlaces Tetiaroa Portal"
theme = "kube"
googleAnalytics = ""
description = "iPlaces is a portal of resources about a specific stewarded place."
Paginate = 4
enableRobotsTXT = true
canonifyURLs = true
[Params]
logo = "/img/Ensatina_closeup_Yap_1024.jpg"


[[menu.main]]
    name = "Projects"
    weight = 4
    url = "/projects/"
[[menu.main]]
    name = "Query"
    weight = 1
    url = "/query/"
[[menu.main]]
    name = "Blog"
    weight = 5
    url = "/blog/"
[[menu.main]]
    name = "Contribute Data"
    weight = 3
    url = "/contributing/"
[[menu.main]]
    name = "Dashboard"
    weight = 2
    url = "/dashboard/"
